import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Inter } from "next/font/google";
import {NuqsAdapter} from "nuqs/adapters/next/app";
import {ConvexClientProvider} from "@/components/convex-client-provider";

export const metadata: Metadata = {
  title: "Google Docs",
  description: "Generated by create next app",
};

const inter =  Inter({
    subsets:["latin"]
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <NuqsAdapter>
            <ConvexClientProvider>
                {children}
            </ConvexClientProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
